server:
  port: 8081

# -- Default spring configuration
spring:
  application:
    name: user

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3bdd477e0baccd07c4369a4cf8c31ed4
            client-secret: 5qAnQWrFYkaO5inuXcDrvQbW5t6lejlR
            redirect-uri: https://ddib.kro.kr/login/oauth2/code/ddib
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
            scope: account_email, profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    generate-ddl: true
  #    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10c102.p.ssafy.io:3306/ddib?useSSL=false&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  data:
    redis:
      host: redis-master.default.svc.cluster.local
      port: 6379

  jwt:
    secret: adkafjlsdjgldkfjskdlakjdjkfljdkjkdkkkksjakslfejfghlajsdflaksjdgljadk

access:
  token:
    expiration:
      time: 3600000

refresh:
  token:
    expiration:
      time: 864000000

releaseHostName: ddib.kro.kr


#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#      base-path: /actuator/user
#  endpoint:
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
#  metrics:
#    export:
#      prometheus:
#        enabled: true
