server:
  port: 8085

# -- Default spring configuration
spring:
  application:
    name: seller

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e75a5a3c4aa3d8065eb63d4c9e4942cc
            client-secret: 7vcu5a0kvnkJbaST7BsNtnsHZ60PMEAq
            redirect-uri: https://k10c102.p.ssafy.io/login/oauth2/code/bidd
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
            scope: account_email, profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    generate-ddl: true
  #    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10c102.p.ssafy.io:3306/ddib?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  data:
    redis:
      host: k10c102.p.ssafy.io
      port: 6379

  jwt:
    secret: adkafjlsdjgldkfjskdlakjdjkfljdkjkdkkkksjakslfejfghlajsdflaksjdgljadk

access:
  token:
    expiration:
      time: 3600000

refresh:
  token:
    expiration:
      time: 864000000

releaseHostName: k10c102.p.ssafy.io

eureka:
  instance:
    hostname: k10c102.p.ssafy.io
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k10c102.p.ssafy.io:8761/eureka/