server:
  port: 8082

# -- Default spring configuration
spring:
  servlet:
    multipart:
      maxFileSize: 5000MB
      maxRequestSize: 5000MB
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddib?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: 1234
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        show_sql: true
#        format_sql: true
  batch:
    jdbc:
      initialize-schema: always

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://127.0.0.1:9411/api/v2/spans"

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}


logging:
  level:
    com:
      ddib:
        product: info
  config: classpath:logback-dev.xml

feign-client:
  notification: http://localhost:8084