server:
  port: 9010

scheduler:
  enabled: true

# -- Default spring configuration
spring:
  application:
    name: waiting
  data:
    redis:
      host: ddib.kro.kr
      port: 6379

# metric 설정
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /actuator/waiting
  metrics:
    export:
      prometheus:
        enabled: true


#eureka:
#  instance:
#    hostname: k10c102.p.ssafy.io
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://k10c102.p.ssafy.io:8761/eureka