server:
  port: 8081

# -- Default spring configuration
spring:
  application:
    name: user

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3bdd477e0baccd07c4369a4cf8c31ed4
            client-secret: 5qAnQWrFYkaO5inuXcDrvQbW5t6lejlR
            redirect-uri: http://localhost:8081/login/oauth2/code/ddib
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
            scope: account_email, profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#    jpa:
#      hibernate:
#        ddl-auto: update
#      generate-ddl: true
#      show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddib?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: adkafjlsdjgldkfjskdlakjdjkfljdkjkdkkkksjakslfejfghlajsdflaksjdgljadk


access:
  token:
    expiration:
      time: 3600000

refresh:
  token:
    expiration:
      time: 864000000

releaseHostName: k10c102.p.ssafy.io

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}