server:
  port: 8084

# -- Default spring configuration
spring:
  application:
    name: notification

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.182.0.18:3306/ddib?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  jpa:
    #    hibernate:
    #      ddl-auto: update
    generate-ddl: true
    show-sql: true

    # -- GMail
  mail:
    host: smtp.gmail.com
    port: 587
    username: hjaehyeon98@gmail.com
    password: wtkm aqnq jusz civw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# -- Eureka client
#eureka:
#  instance:
#    hostname: k10c102.p.ssafy.io
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://k10c102.p.ssafy.io:8761/eureka/d

releaseHostName: ddib.kro.kr

project:
  properties:
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "ddib_subscribe_notification"