server:
  port: 8000

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**, /api/oauth2/ddib/kakao, /login/oauth2/code/ddib/**, /login/done
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

#        - id: user
#          uri: lb://USER
#          predicates:
#            - Path=/api/oauth2/ddib/kakao
#            - Path=
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: seller
          uri: lb://seller
          predicates:
            - Path=/api/seller/**, /api/oauth2/bidd/kakao, /login/oauth2/code/bidd/**, /login/done/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/notification/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilterx

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/product/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/payment/**, /api/order/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

        - id: waiting
          uri: lb://waiting
          predicates:
            - Path=/api/v1/queue/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowed-origin-patterns: "*"
#            allowedOrigins:
#              - "http://k10c102.p.ssafy.io/"
#              - "https://k10c102.p.ssafy.io/"
#              - "http://localhost:3000/"
#              - "https://localhost:3000/"
#              - "http://localhost/"
#              - "https://localhost/"
#            allow-credentials: true
#            allowedHeaders: "*"
#              - x-requested-with
#              - authorization
#              - content-type
#              - credential
#              - X-AUTH-TOKEN
#              - X-CSRF-TOKEN
#            allowedMethods:
#              - POST
#              - GET
#              - PUT
#              - PATCH
#              - OPTIONS
#              - DELETE

#springdoc:
#  enable-native-support: true
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    urls:
#      - url: /user/swagger-ui/index.html
#        name: User
#      - url: /seller/swagger-ui/index.html
#        name: Seller
#      - url: /notification/swagger-ui/index.html
#        name: Notification
#      - url: /product/swagger-ui/index.html
#        name: Product
#      - url: /payment/swagger-ui/index.html
#        name: Payment
#      - url: /waiting/swagger-ui/index.html
#        name: Waiting
#    use-root-path: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'https://k10c102.p.ssafy.io/'
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
#            allowCredentials: true
#            maxAge: 3600


jwt:
  secret: adkafjlsdjgldkfjskdlakjdjkfljdkjkdkkkksjakslfejfghlajsdflaksjdgljadk

eureka:
  instance:
    hostname: k10c102.p.ssafy.io
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k10c102.p.ssafy.io:8761/eureka/