server:
  port: 8000

# -- Default spring configuration
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
        - id: seller
          uri: http://localhost:8085
          predicates:
            - Path=/api/seller/**
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/api/notification/**
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/api/payment/**

# -- Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}