server:
  port: 8000

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://k10c102.p.ssafy.io
          predicates:
            - Path=/api/user/**, /login/oauth2/code/ddib
          filters:
            - AuthorizationHeaderFilter

        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/oauth2/ddib/kakao

        - id: seller
          uri: lb://SELLER
          predicates:
            - Path=/api/seller/**
          filters:
            - AuthorizationHeaderFilter

        - id: seller
          uri: lb://SELLER
          predicates:
            - Path=/api/oauth2/bidd/**

        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/notification/**
          filters:
            - AuthorizationHeaderFilter

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/product/**
          filters:
            - AuthorizationHeaderFilter

        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/payment/**, /api/order/**
          filters:
            - AuthorizationHeaderFilter

        - id: waiting
          uri: lb://WAITING
          predicates:
            - Path=/api/v1/queue/**
          filters:
            - AuthorizationHeaderFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://k10c102.p.ssafy.io/"
              - "https://k10c102.p.ssafy.io/"
              - "http://localhost:3000/"
              - "https://localhost:3000/"
              - "http://localhost/"
              - "https://localhost/"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE

#springdoc:
#  enable-native-support: true
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    urls:
#      - url: /user/swagger-ui/index.html
#        name: User
#      - url: /seller/swagger-ui/index.html
#        name: Seller
#      - url: /notification/swagger-ui/index.html
#        name: Notification
#      - url: /product/swagger-ui/index.html
#        name: Product
#      - url: /payment/swagger-ui/index.html
#        name: Payment
#      - url: /waiting/swagger-ui/index.html
#        name: Waiting
#    use-root-path: true

jwt:
  secret: adkafjlsdjgldkfjskdlakjdjkfljdkjkdkkkksjakslfejfghlajsdflaksjdgljadk

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://k10c102.p.ssafy.io:8761/eureka/}