server:
  port: 8000

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - AuthorizationHeaderFilter

        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/oauth2/ddib/**

        - id: seller
          uri: http://localhost:8085
          predicates:
            - Path=/api/seller/**
          filters:
            - AuthorizationHeaderFilter

        - id: seller
          uri: http://localhost:8085
          predicates:
            - Path=/api/oauth2/bidd/**

        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/api/notification/**
          filters:
            - AuthorizationHeaderFilter

        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**
          filters:
            - AuthorizationHeaderFilter

        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/api/payment/**, /api/order/**
          filters:
            - AuthorizationHeaderFilter

        - id: waiting
          uri: http://localhost:9010
          predicates:
            - Path=/api/v1/queue/**
          filters:
            - AuthorizationHeaderFilter

jwt:
  secret: adkafjlsdjgldkfjskdlakjdjkfljdkjkdkkkksjakslfejfghlajsdflaksjdgljadk

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}