# -- Server Port
server:
  port: 8761

spring:
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
# -- Eureka
eureka:
  instance:
    hostname: k10c102.p.ssafy.io
  client:
    serviceUrl:
      defaultZone: http://k10c102.p.ssafy.io:8761/eureka
    register-with-eureka: false
    fetch-registry: false
