# -- Server Port
server:
  port: 8761

# -- Eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://k10c102.p.ssafy.io:8761/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  profiles:
    active: dev
