# -- Server Port
server:
  port: 8761

spring:
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
# -- Eureka
eureka:
  instance:
    hostname: k10c102.p.ssafy.io
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
