server:
  port: 8084

# -- Default spring configuration
spring:
  application:
    name: notification

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10c102.p.ssafy.io:3306/ddib?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true

    # -- GMail
  mail:
    host: smtp.gmail.com
    port: 587
    username: hjaehyeon98@gmail.com
    password: wtkm aqnq jusz civw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

releaseHostName: ddib.kro.kr

# -- Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}

project:
  properties:
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "ddib_subscribe_notification"
